### ISSUE TITLE
Cannot find name of docker container

### ISSUE THREAD

**Issue by kmlucy** [titpetric/netdata#10]
When I create and start the netdata docker container with:

`docker create --name=netdata --cap-add=SYS_PTRACE -v /proc:/host/proc:ro -v /sys:/host/sys:ro -v /var/run/docker.sock:/var/run/docker.sock -p 19998:19999 titpetric/netdata`

The logs show several of these errors, and the names of the containers are all c****\* online:

`Running API command: /containers/c73555999a92327cdb8acdc264b5577256196aa9bf08483bbac23720560de520/json
nc: unix connect failed: Permission denied
Cannot find the name of docker container 'c73555999a92327cdb8acdc264b5577256196aa9bf08483bbac23720560de520'
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'docker/c73555999a92327cdb8acdc264b5577256196aa9bf08483bbac23720560de520' is called 'c73555999a92'`

Is there a fix for this?

Thanks,
Kyle

**Comment by titpetric** [comment]
It seems to be a permissions problem. You can use docker-proxy-acl to forward a secure proxy. Please see this blog entry for instructions: https://scene-si.org/2016/04/25/exposing-your-docker-api/ (it might also be covered with the readme on the [docker-proxy-acl repo](https://github.com/titpetric/docker-proxy-acl)).

**Comment by kmlucy** [comment]
That fixed it. Thanks for the quick response.
