### ISSUE TITLE
nc: unix connect failed: Permission denied

### ISSUE THREAD

**Issue by blaines** [titpetric/netdata#18]
From the docker logs...

It seems like `nc` isn't being allowed from some reason? I tried nc and the script manually and it worked just fine.

```
nc: unix connect failed: Permission denied
Cannot find the name of docker container '82735a68dc95b947a43edfe3c4cad03d5b6d563e88033c36b83de1063ada5a2c'
/etc/netdata/overrides/cgroup-name.sh: cgroup 'docker_82735a68dc95b947a43edfe3c4cad03d5b6d563e88033c36b83de1063ada5a2c' is called '82735a68dc95'
Running API command: /containers/cd1bbb3d665ae5028467efeea36190793694b8cfd954220af5e2d8869340206e/json
nc: unix connect failed: Permission denied
Cannot find the name of docker container 'cd1bbb3d665ae5028467efeea36190793694b8cfd954220af5e2d8869340206e'
/etc/netdata/overrides/cgroup-name.sh: cgroup 'docker_cd1bbb3d665ae5028467efeea36190793694b8cfd954220af5e2d8869340206e' is called 'cd1bbb3d665a'
Running API command: /containers/e405a61d3c58ca53c25f629bc824302c8ce7fcabb68ab27ef64f93489a483151/json
nc: unix connect failed: Permission denied
Cannot find the name of docker container 'e405a61d3c58ca53c25f629bc824302c8ce7fcabb68ab27ef64f93489a483151'
/etc/netdata/overrides/cgroup-name.sh: cgroup 'docker_e405a61d3c58ca53c25f629bc824302c8ce7fcabb68ab27ef64f93489a483151' is called 'e405a61d3c58'
Running API command: /containers/f74e5cea16b691067ff260dc39eba254285cde758f95d16230b69715fc489825/json
nc: unix connect failed: Permission denied
Cannot find the name of docker container 'f74e5cea16b691067ff260dc39eba254285cde758f95d16230b69715fc489825'
/etc/netdata/overrides/cgroup-name.sh: cgroup 'docker_f74e5cea16b691067ff260dc39eba254285cde758f95d16230b69715fc489825' is called 'f74e5cea16b6'
```

**Comment by blaines** [comment]
Actually I think it's related to this issue, as my script is modified slightly and uses root as the user...

https://github.com/docker/docker/issues/2259

**Comment by blaines** [comment]
can reproduce by:

```
su -c "/etc/netdata/overrides/cgroup-name.sh docker_7ced9b865453692bc3a71fff5913b9215057c7089d70f5446f8e08629c1c5638" -s /bin/bash netdata
Running API command: /containers/7ced9b865453692bc3a71fff5913b9215057c7089d70f5446f8e08629c1c5638/json
nc: unix connect failed: Permission denied
Cannot find the name of docker container '7ced9b865453692bc3a71fff5913b9215057c7089d70f5446f8e08629c1c5638'
/etc/netdata/overrides/cgroup-name.sh: cgroup 'docker_7ced9b865453692bc3a71fff5913b9215057c7089d70f5446f8e08629c1c5638' is called '7ced9b865453'
7ced9b865453
```

**Comment by blaines** [comment]
So it looks like this is caused by `/var/run/docker.sock` being owned by root

**Comment by blaines** [comment]
Changing the netdata.conf file by modifying the setting:

```
[global]
    run as user = root
```

Resolved the issue. Though I believe the sysadmin gods would banish me for that, it works.

I think the docs should be updated a bit, but `docker-proxy-acl` probably should be advertised as a requirement. Ideally `docker-proxy-acl` would expose a new socket that could be used in containers.

https://github.com/titpetric/docker-proxy-acl

**Comment by kmlucy** [comment]
I built a docker container for `docker-proxy-acl` that is a little easier to set up here: https://github.com/kmlucy/docker-proxy-acl

**Comment by titpetric** [comment]
It would actually make sense for netdata to run as root in the container regardless. @ktsaou, is there perhaps a runtime option argument available for this (-u root?).

**Comment by ktsaou** [comment]
like you said: `-u root`. It can also be set in `netdata.conf`: `run as user` setting.

**Comment by titpetric** [comment]
@ktsaou Thank you, it's easier for me to add `-u root` so I've just gone ahead and did that. Marking issue as closed.

**Comment by ktsaou** [comment]
Mine though is different:

``` sh
# ls -l /var/run/docker.sock
srw-rw---- 1 root docker 0 Sep 25 16:20 /var/run/docker.sock
```

If you add user `netdata` to the `docker` group, it will work. netdata-installer.sh already does this: https://github.com/firehol/netdata/blob/a413b46d1abff0d78aaa104d14951c94ee580c18/netdata-installer.sh#L561-L577

**Comment by ktsaou** [comment]
> netdata-installer.sh already does this

it does it only when the docker group exists of course...

**Comment by titpetric** [comment]
@ktsaou - true, it's a permissions issue. But as netdata is running in a container, there's no reasonable restriction why it shouldn't run as root in the first place, as UID mapping will take place with Docker in due time. The use of `docker-proxy-acl` is still recommended to provide a "safe" docker.sock file, which is another way to [touch the fishy](http://imgur.com/gallery/ZigXHzX) in this case.

**Comment by ktsaou** [comment]
> The use of docker-proxy-acl is still recommended to provide a "safe" docker.sock file, which is another way to touch the fishy in this case

why don't we use it then?
what needs to be done?

**Comment by titpetric** [comment]
@ktsaou it's optional, we can't enforce use beyond documentation.

**Comment by blaines** [comment]
Just wanted to come back and say thanks @titpetric @kmlucy for fixing this issue so quickly! I'm already using it!
