### ISSUE TITLE
Why build.sh ?

### ISSUE THREAD

**Issue by MBuffenoir** [titpetric/netdata#2]
Hello,

Just wondering why not put all the instructions in the Dockerfile instead of build.sh (thus taking advantages of the union filesystem) ?

**Comment by titpetric** [comment]
Technically, I could, but it's more readable this way. The result would be the same, in the sense of producing an image layer the same as it's built from build.sh today. But build.sh can easily include logic, comments, and can be reviewed by people who are familiar with bash, but perhaps not so much familiar with Dockerfiles.

In the end, it seems a personal preference. If you like it inline, feel free to fork/...
