### ISSUE TITLE
can not run with latest docker image

### ISSUE THREAD

**Issue by paranoid945** [titpetric/netdata#20]
after docker run successfully, and I open browser with http://xxxx:19999, I get this error message:

Access to file '/usr/share/netdata/web/' is not permitted.

**Comment by kmlucy** [comment]
This is due to netdata now being run as root. See firehol/netdata#1051.
As a temporary fix, run:

```
docker exec netdata chown -R root:root /usr/share/netdata/web/
```

**Comment by titpetric** [comment]
Chmod added, image should be built in a few minutes.

**Comment by titpetric** [comment]
Confirming it works. Closing.
