### ISSUE TITLE
How can I update to latest version? (question)

### ISSUE THREAD

**Issue by joseluisq** [titpetric/netdata#21]
![captura de pantalla 2016-10-20 a las 13 02 41](https://cloud.githubusercontent.com/assets/1700322/19571909/85800e84-96c5-11e6-888c-ecc58c289770.png)

**Comment by kmlucy** [comment]
You just have to pull the new version, remove your current container, and run a new one. I have a script run nightly to do so: 

```
docker stop netdata 
docker rm netdata
docker pull titpetric/netdata 
docker run --name=netdata ... 
```

**Comment by joseluisq** [comment]
Apparently it doesn't work:

``` sh
~> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                      NAMES
b12a69ab8b64        titpetric/netdata   "/run.sh"           44 seconds ago      Up 44 seconds       0.0.0.0:19999->19999/tcp   dreamy_banach

~> docker stop b12a69ab8b64
b12a69ab8b64

~> docker rm b12a69ab8b64
b12a69ab8b64

~> docker pull titpetric/netdata
latest: Pulling from titpetric/netdata

d0c4f1eb7dc8: Already exists
faeaf6fdfdcb: Already exists
42a13af980cf: Already exists
09b58f27d3f6: Already exists
7dd6e3b490fe: Already exists
d74f266be060: Already exists
5c902be36283: Already exists
962c50c7da35: Already exists
7ad2429cb6a1: Already exists
Digest: sha256:12da854267403ccea8fe4cbf0606efd80e6346ed7ae08f61cc8fc4e0d0f56c8b
Status: Image is up to date for titpetric/netdata:latest

~> docker run -d --cap-add SYS_PTRACE \
                           -v /proc:/host/proc:ro \
                           -v /sys:/host/sys:ro \
                           -p 19999:19999 titpetric/netdata
729b99a6e0f9545ff5a3d3dec2c41a235ee6065df2d2fe72380ca85694f5c069
```

Then:

```
Update Check
Your netdata version: cc629d07bbf8986a7630d810cacf94fca58d566b 
New version of netdata available!

Latest version: c9e318603b7cbfa65203d38431f43c5375f0118c

Click here for the changes log since your installed version, and
click here for directions on updating your netdata installation.
```

**Comment by kmlucy** [comment]
Looks like @titpetric will have to trigger a build.

**Comment by titpetric** [comment]
Latest build failed for some reason, it will be triggered on new commits, but I'll make sure to do it manually asap. The docker hub version you're pulling should always be the latest, hopefully it's just some intermittent issue with hub.

**Comment by joseluisq** [comment]
:+1:

**Comment by titpetric** [comment]
It seems that docker hub has issues, can't find build.sh on build step. I triggered the build manually and hope it will be resolved. It seems like some general error in regards to docker hub, and should be safe to ignore this, as long as you're willing to accept that you can't always run the most-recent version.

@ktsaou is there a way to turn off these checks with some command line argument, to make the experience more user friendly?

**Comment by ktsaou** [comment]
> is there a way to turn off these checks with some command line argument, to make the experience more user friendly?

which checks?

**Comment by kmlucy** [comment]
I think it may have something to do with the massive DDoS attack. I believe it affected GitHub.

**Comment by titpetric** [comment]
@ktsaou - the check if running netdata is up to date, is there a way to disable it? In terms of netdata docker image it may be redundant to have this check as the image is built automatically.

Also: closing issue as it's the problem of Docker hub, I see no way to resolve it at the moment

**Comment by ktsaou** [comment]
Just empty `/usr/share/netdata/web/version.txt`. The check will go away...
