### ISSUE TITLE
cat /host/proc/[pid]/io permission dennied

### ISSUE THREAD

**Issue by pando85** [titpetric/netdata#27]
I coudn't open /host/proc/[pid]/io.
I added `--security-opt=apparmor:unconfined` at running container found it in [docker#7276](https://github.com/docker/docker/issues/7276#issuecomment-194137403).
Now it's working correctly.

**Comment by titpetric** [comment]
What would be the complete `docker run` statement which you are running? I suppose that not reading the `host/proc/pid/io` would result in the lack of docker disk io metrics? Currently I only experienced limitations without --cap-add=SYS_PTRACE, so this may be included in the README, If I can reproduce the issue.

**Comment by pando85** [comment]
I'm running it with docker-compose:
```compose
version: '2'
services:
  netdata:
    image: titpetric/netdata 
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/log/:/var/log/:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./netdata/:/etc/netdata/
      - /home/server/data2:/home/server/data2:ro
      - /home/server/data1:/home/server/data1:ro
    network_mode: host
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
```

`data1` and `data2` is for monitoring filesystem, and `/var/log` for nginx_log plugin.

Not reading [/host/proc/[pid]/io] cause a block in apps.plugin log, but I don't know what metrics are affected:
```
Dec  6 12:32:01 server docker/netdata_netdata_1[8562]: 2016-12-06 11:32:01: apps.plugin: Too many logs (101 logs in 1 seconds, threshold is set to 100 logs in 3600 seconds). Preventing more logs from process 'apps.plugin' for 3599 seconds.
```

**Comment by titpetric** [comment]
Can't confirm issue, closing. Only SYS_PTRACE is needed.
