### ISSUE TITLE
Docker container names don't work on Red Hat Enterprise Linux Server?

### ISSUE THREAD

**Issue by 2Fast2BCn** [titpetric/netdata#31]
Run command:
> docker run -d --cap-add SYS_PTRACE -v /proc:/host/proc:ro -v /sys:/host/sys:ro -v /var/run/docker.sock:/var/run/docker.sock --net=host titpetric/netdata

From the logs:
> 2016-12-29 09:27:40: cgroup-name.sh: INFO: Running API command: /containers/d16e0400a2efe52787ebd95a71e0ad2404e847e8a876a35d1b1c86d59bbdd14d/json
> nc: unix connect failed: Permission denied
> 2016-12-29 09:27:40: cgroup-name.sh: WARNING: cannot find the name of docker container 'd16e0400a2efe52787ebd95a71e0ad2404e847e8a876a35d1b1c86d59bbdd14d'
> 2016-12-29 09:27:40: cgroup-name.sh: INFO: cgroup 'system.slice_docker-d16e0400a2efe52787ebd95a71e0ad2404e847e8a876a35d1b1c86d59bbdd14d.scope' is called 'd16e0400a2ef'

With Regards.

**Comment by titpetric** [comment]
It's a known permissions issue. Make docker.sock world readable (chmod a+r
docker.sock on the host).

Best,
Tit

**Comment by 2Fast2BCn** [comment]
> ll /var/run/
> srw-rw-r--.  1 root     root        0 Dec 29 09:44 docker.sock

> 2016-12-30 09:02:36: cgroup-name.sh: INFO: Running API command: /containers/d14eaf1d3d4b462579430805c569ae16c4aef8d85205504a49e76b6be0277e74/json
> nc: unix connect failed: Permission denied
> 2016-12-30 09:02:36: cgroup-name.sh: WARNING: cannot find the name of docker container 'd14eaf1d3d4b462579430805c569ae16c4aef8d85205504a49e76b6be0277e74'
> 2016-12-30 09:02:36: cgroup-name.sh: INFO: cgroup 'system.slice_docker-d14eaf1d3d4b462579430805c569ae16c4aef8d85205504a49e76b6be0277e74.scope' is called 'd14eaf1d3d4b'

I must be doing something wrong?
I'm running Red Hat Enterprise Linux Server release 7.3 (Maipo)
With docker version 1.10.3
Kernel Version: 3.10.0-327.36.1.el7.x86_64

With Regards.

**Comment by titpetric** [comment]
Hi,

please try to issue `chown root.docker /var/run/docker.sock`.

~~~
srw-rw---- 1 root docker 0 Nov  7 11:01 /var/run/docker.sock
~~~

Best,
Tit

**Comment by 2Fast2BCn** [comment]
group docker doesn't exist on my system (dockerroot does so I tried that but it doesn't change anything)

> srw-rw-r--.  1 root     dockerroot    0 Dec 29 09:44 docker.sock

**Comment by titpetric** [comment]
as what user are you running docker? root, or local user with sudo? I feel you'll need to find out how to grant access to the docker.sock file for use in docker containers on your operating system on your own.

http://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/
https://github.com/projectatomic/atomic-site/issues/161
 or other sites. Good luck.
