### ISSUE TITLE
psycopg2 dependency

### ISSUE THREAD

**Issue by pando85** [titpetric/netdata#32]
What must I do if I want to monitor my postgres databases?

**Comment by titpetric** [comment]
Please consult the upstream project documentation (firehol/netdata). If software is missing from the container, it's up to you to extend/install additional software. This docker image is meant to provide basic monitoring, and doesn't cover out of scope applications which you as the user might have. For example, you might have a UPS that can be monitored by netdata, but it is not the goal of this image to support this. As such, you can either 1) extend the image with additional software, 2) install netdata without docker isolation and manage your software as you do now (ansible, chef, etc.).
