### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by DarkIsDude** [titpetric/netdata#35]
Hi,

I'm on ubuntu 16.04.1 LTS (Xenial Xerus) with Docker version 1.13.0, build 49bf474.
When I run this:

```
docker run -d --cap-add SYS_PTRACE \
>            -v /proc:/host/proc:ro \
>            -v /sys:/host/sys:ro \
>            -p 19999:19999 titpetric/netdata
```

I have this
```
docker logs ecstatic_bassi -f
/run.sh: line 27: conditional binary operator expected
/run.sh: line 27: syntax error near `[['
/run.sh: line 27: `if [[ $SLACK_WEBHOOK_URL ]]; then'
```

Can you help me?

**Comment by Djamy** [comment]
Hi,

I have the same issue, something's wrong [here](https://github.com/titpetric/netdata/blob/master/run.sh#L25) in [this commit](https://github.com/titpetric/netdata/commit/2a7959671596aa13e4255c1910f0b21b707e43af).

**Comment by clok** [comment]
Same here... made a duplicate issue with details by accident #37

**Comment by clok** [comment]
This is the offending commit: https://github.com/titpetric/netdata/commit/2a7959671596aa13e4255c1910f0b21b707e43af#diff-1b0c2b516b83393edb7200ad5ff12181R25

**Comment by titpetric** [comment]
Sorry. Fixed in upstream. Build should be on DH shortly.
