### ISSUE TITLE
Latest commit has syntax error

### ISSUE THREAD

**Issue by clok** [titpetric/netdata#37]
When pulling latest from Dockerhub there is an syntax error on startup:

```
1/26/2017 6:41:38 AM/run.sh: line 27: conditional binary operator expected
1/26/2017 6:41:38 AM/run.sh: line 27: syntax error near `[['
1/26/2017 6:41:38 AM/run.sh: line 27: `if [[ $SLACK_WEBHOOK_URL ]]; then'
```

This is the build in Dockerhub: https://hub.docker.com/r/titpetric/netdata/builds/bmmryqfs6pjtnodxmkgaqhq/

This is the offending commit: https://github.com/titpetric/netdata/commit/2a7959671596aa13e4255c1910f0b21b707e43af#diff-1b0c2b516b83393edb7200ad5ff12181R25

**Comment by titpetric** [comment]
Sorry. Fixed in upstream. Build should be on DH shortly.
