### ISSUE TITLE
Make a Dev Branch?

### ISSUE THREAD

**Issue by JoeStratton** [titpetric/netdata#40]
Not an issue but this is the only container I see that gets updates twice a day, which is excessive to most standards. Have you thought about creating a test/dev branch and only pushing to master X amount of days/commits? 

This is not a complaint! Great work.

**Comment by titpetric** [comment]
Technically, I could turn off pushing for tagged releases, docker hub seems to update them all... and master goes to :latest which is definitely fine. I have to monitor upstream for a bit, just to see if maybe I should just manually push versioned/tagged images ...

**Comment by titpetric** [comment]
- deactivated builds for tagged images, only latest gets updated now.
