### ISSUE TITLE
new 1.6 tag always updating with latest tag

### ISSUE THREAD

**Issue by JoeStratton** [titpetric/netdata#43]
Hi, great work as always.
I previously requested having the 1.5 tag not update every time you push to latest, but now with the release of 1.6 it seems to have reset.

Can you make it so 1.6 does not update so often once again?

Thanks!

**Comment by titpetric** [comment]
Done, but generally it's not so much an issue as the tag doesn't move in the repo. It's just unfortunate :) maybe I'll just build it manually once in the future. Thanks for the heads up.

**Comment by JoeStratton** [comment]
Yea i figured it wasnt an "issue" but this was the best way I knew of reaching out. Thanks for taking care of that!
