### ISSUE TITLE
Give an example of docker-compose.yml

### ISSUE THREAD

**Issue by murbanowicz** [titpetric/netdata#46]
Hi,
Would be great to have example of docker-compose.yml so we would know how to use it with compose.
In my particular case I want to use it in container behing nginx+nginx-gen and so far I have no idea how to start.

**Comment by titpetric** [comment]
Hello,

this should be a good example to start:
https://github.com/rancher-cowboys/catalog/blob/master/templates/netdata/0/docker-compose.yml

You could also consult the official compose documentation, to convert the example docker run command into the appropriate docker-compose.yml config.

Best,
Tit
