### ISSUE TITLE
Any way to get stats on host net interfaces without passing --net=host when running

### ISSUE THREAD

**Issue by byrnedo** [titpetric/netdata#5]
Do you know of any way to do that?

**Comment by titpetric** [comment]
~~It seems currently the plugin doesn't support it. I'd suggest reporting an issue on firehol/netdata if you're depending on this feature.~~

Edit: I've did some research, and it's a limitation of how linux namespacing works. Please see this issue for an explanation: [network interfaces missing when mounting proc inside a container](https://github.com/docker/docker/issues/13398). I will be updating the README and closing this issue when I do.

**Comment by titpetric** [comment]
Updated docs to reflect this issue.
