### ISSUE TITLE
version 1.8 is out

### ISSUE THREAD

**Issue by pascalandy** [titpetric/netdata#50]
I checked your Dockerfile but I can't see quickly where you defined the version. 
I'll be glad to see a PR from 1.6 to 1.8 so I can understand how your Dockerfile setup is working :)

https://github.com/firehol/netdata/releases

Thank you very much for having put this together!

**Comment by pascalandy** [comment]
Well, I just saw this PR https://github.com/titpetric/netdata/pull/49/commits/a34d2795fa1e25b6ae4ffad50435f75d36ed2e47

Cheers!

**Comment by titpetric** [comment]
Already merged into master, and generally the dockerfile setup is documented in README.md. The new releases should be built and on docker hub soon.
