### ISSUE TITLE
Show container id instead of host name

### ISSUE THREAD

**Issue by tumluliu** [titpetric/netdata#51]
This is really a great image that make our netdata-related work much easier. Thanks a lot for your work! We found, however, the machine name displayed on the webpage is the container id which is very unintuitive (as shown in the screenshot). Is it possible to change it to the real hostname of the monitored host as in the native installed netdata? 

<img width="320" alt="screen shot 2017-09-27 at 17 12 09" src="https://user-images.githubusercontent.com/1563792/30922276-f288fd88-a3a8-11e7-8cd3-f583150c8da1.png">

**Comment by titpetric** [comment]
It sure is, linking the readme for more info:

https://github.com/titpetric/netdata#monitoring-docker-container-metrics

This will show the hostname set in the container (and not the host, however). I suppose this is what you want, as you can set the container hostname to anything with `-h` option. :)

Best,
Tit

**Comment by tumluliu** [comment]
thanks a lot! the `-h` is what I am looking for :)
