### ISSUE TITLE
Add an override volume for /usr/libexec/netdata

### ISSUE THREAD

**Issue by dcflachs** [titpetric/netdata#58]
Would it be possible to add an override volume for "/usr/libexec/netdata" like the one that exists for "/etc/netdata"? I would like to be able to insert a new python.d charts module into /usr/libexec/netdata/python.d

**Comment by titpetric** [comment]
If you use docker `-v` option, you could pass anything you like to netdata. What exactly am I/.are you missing here?

**Comment by titpetric** [comment]
If you're looking at:

~~~
VOLUME /etc/netdata/override
~~~

In the Dockerfile, this is just a documentation flag, much like EXPOSE. It only tells you which volumes are meant for mounting, but it doesn't prevent you from mounting your own `/usr/libexec/netdata` or any other location.

**Comment by dcflachs** [comment]
Unless I am mistaken the /etc/netdata/override folder is a mechanism of your docker container and not of Netdata itself. You somehow take the files/folders in /etc/netdata/override and overlay them on the /etc/netdata/ directory at runtime.

**Comment by dcflachs** [comment]
That allows overriding or adding files to /etc/netdata without effecting the other files in that directory.

**Comment by titpetric** [comment]
True, but if you want to include something outside of netdata into the
container, you can just use -v volume mount, either to mount a whole folder
or a specific file.

**Comment by dcflachs** [comment]
I was not aware that -v could be used for a single file. I will try that, thank you. If I may ask though, what is the purpose of /etc/netdata/override considering the above?

**Comment by titpetric** [comment]
The override location is there for convenience. When you pass it to the container, it will copy the files from it into /etc/netdata:

~~~
for f in /etc/netdata/override/*; do
  cp -a $f /etc/netdata/
done
~~~

If you would use something like `-v /opt/netdata/override/sensors.conf:/etc/netdata/sensors.conf` it would have the same effect, but it would be a bit long to say the least if you wanted to pass every file.

In your case, you can either make a new Dockerfile, and use ADD to include your specific python plugins and build a new docker image, or you can provide said plugin with a volume mount, if it's practical for you. Not sure that I'll be adding other override locations in the future, override is there purely for convenience reasons (ie, is used more often than passing custom charts modules,...).

I'd go with a new Dockerfile if this is something that you'll use all the time.
