### ISSUE TITLE
Allow config options to be set on container command line

### ISSUE THREAD

**Issue by ktsaou** [titpetric/netdata#59]
@titpetric on gitter a few folks asked for a method to set config option to netdata inside the container.

I suggested to them to change dockerfile, like that:

```
CMD /usr/sbin/netdata -D -s /host -p ${NETDATA_PORT} ${NETDATA_CONF_SET} -c /etc/netdata.conf ${NETDATA_CONF_DEF}
```

These variables support this format:

```
NETDATA_CONF_SET="-W set 'plugins' 'tc' 'no' -W set 'section with space' 'setting with space' 'value with space' ..."
```

The 2 different variables are used like this:

- `NETDATA_CONF_SET` all config options set with this, override `netdata.conf`
- `NETDATA_CONF_DEF` all config options set with this, set the default values, that can be overridden by editing `netdata.conf`.

What do think? Should we add them by default?

**Comment by titpetric** [comment]
I'm thinking I'm going to add "$@" to the command line itself, avoiding any env variables. The entrypoint basically points to /usr/sbin/netdata (run.sh, but exec replaces pid 1). Any options can be passed via CMD, not sure there's a need for default values, at least I can't think of one that I'd want to override, apart from NETDATA_PORT...

I'll go ahead and add the "$@" to pass all arguments to netdata, and think a bit more about any defaults. Generally I could add them to `CMD` (which I don't use at this moment), and you'd basically overwrite them anytime you pass anything as the docker run argument...

**Comment by titpetric** [comment]
Done. Happy new year ;)
