### ISSUE TITLE
Please trigger a docker hub build

### ISSUE THREAD

**Issue by DavidSichau** [titpetric/netdata#6]
Could you please trigger a new build as the bug firehol/netdata#329 cause me some problems.

**Comment by titpetric** [comment]
Docker hub builds are now automatic based on firehol/netdata repo activity (upstream). They should be created as new commits are pushed.

**Comment by DavidSichau** [comment]
@titpetric I have forked your repo and made some changes that the docker names are correctly identified  inside the container.

This requires that `/var/run/docker.sock` is mounted as a volume and the `netdata` user is added to the docker group.

In addition I switched to centos as the dockerversion for redhat operating systems is 0.9.

I am not sure if these changes are of greater interest.

**Comment by titpetric** [comment]
Hi,

Changes are of greater interest, but slightly inconvenient. If you'll allow me to make some points:
1. Netdata is already adding itself into the docker group. [Source](https://github.com/firehol/netdata/blob/master/netdata-installer.sh#L365).
2. Installing docker within a docker container is a bad idea (version mismatches, security),
3. titpetric/netdata already supports forwarding docker.sock but netdata didn't catch up yet.
4. forwarding docker.sock to a container exposes the complete docker host

That being said, there's a reasonably stable way to limit exposure of docker.sock to a container. I wrote [docker-proxy-acl](https://github.com/titpetric/docker-proxy-acl) just for this purpose. If you glance over the README, you'll find out why it's a bad idea to forward the original docker.sock file.

And as for the current deal breaker, netdata doesn't yet support getting the container names via the docker.sock API directly. It's been mentioned in [issue #115](https://github.com/firehol/netdata/issues/115) which is still pending enhancement. Reliability on the Docker binary is not a long-term solution.

Also, if you'd want to solve #2, currently the only way I'd suggest is to check out my post, [How to live inside a docker container?](https://scene-si.org/2016/04/01/how-to-live-inside-a-docker-container/). You forward the docker binary and libraries to the container. To have a secure way to achieve this, set up 'docker-proxy-acl' along with the volume mount of the binary/libs.

Or just wait until firehol/netdata supports limited API calls. Development of it is very active, so it will not be very long. Also, there are a number of reasons why netdata should run _outside_ of a container, so you may get also other metrics like mysql, etc, this is a valid option to consider. What is isolation adding in your case, if you're forwarding the complete access to your docker host to this container?

Best,
Tit

**Comment by DavidSichau** [comment]
@titpetric Thanks for your comments.

Your points are valid. I will try out the `docker-proxy-aci` container.

The problem is that our deployment is based on docker cloud. Therefore we want every service to live inside a docker container. Therefore it is a complete no go to install netdata outside a container.

I think I will wait some time until API calls are supported.

**Comment by titpetric** [comment]
Mind telling me what pricing you have per node of docker cloud just as a curiosity? I'm looking to install it on a few hosts, if it will be reasonable, but didn't bother sending an e-mail to docker sales yet.

**Comment by DavidSichau** [comment]
At the moment they do not provide any discounts so we pay 15$ per node, we contacted them (The first node is free).

But we changed our vms because of their pricing. We have now 16core vms where on each around 100 docker services are running. Before we had 1 core machines with each around 10 services running.

**Comment by titpetric** [comment]
Yeah, that pricing is very competitive. I read somewhere that dev laptops
also count against free quota? I'd do the same as you did, because I have
10-20 vms that just eat up ram and single cores, for mostly idle services
like dns, mail. It's attractive however for very elastic workloads where
rebooting to add CPUs might be a bit inconvenient. A 16 core VM or a bare
metal install gives you lots of wiggle room there. API services for the
biggest client eat up about 24 cores under high load... and about 5% of
that in normal times :)

**Comment by DavidSichau** [comment]
Thats correct every node counts independent of the size. Also developer laptops.

**Comment by titpetric** [comment]
A PR has been submitted to netdata to allow querying the docker.sock file if the docker binary doesn't exist. This means that you can either forward just `/var/run/docker.sock` to the container, or use docker-proxy-acl to provide a secure version of it.

**Comment by titpetric** [comment]
PR merged. Let me know if it works for you. Only docker.sock needed now
