### ISSUE TITLE
Not getting email notifications

### ISSUE THREAD

**Issue by drmrbrewer** [titpetric/netdata#63]
I've set the various env variables stated in the README, but am still not getting any email notifications... this is despite the occasional alert showing in the console itself (mostly `system.softnet_stat` warnings).

    $ docker container inspect my-netdata-container
    (relevant section only):
	"Config": {
		"Hostname": "d264a2605abx",
		"Domainname": "",
		"User": "",
		"AttachStdin": false,
		"AttachStdout": false,
		"AttachStderr": false,
		"ExposedPorts": {
			"19999/tcp": {}
		},
		"Tty": false,
		"OpenStdin": false,
		"StdinOnce": false,
		"Env": [
			"SSMTP_TO=another-email@gmail.com",
			"SSMTP_HOSTNAME=server-01",
			"SSMTP_SERVER=smtp.gmail.com",
			"SSMTP_PORT=587",
			"SSMTP_TLS=YES",
			"SSMTP_USER=my-email@gmail.com",
			"SSMTP_PASS=my-google-app-password",
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"NETDATA_PORT=19999"
		],
		"Cmd": null,
		"ArgsEscaped": true,
		"Image": "titpetric/netdata:1.8",
		"Volumes": null,
		"WorkingDir": "/",
		"Entrypoint": [
			"/run.sh"
		],
		"OnBuild": null,
		"Labels": {}
	},

Are there any logs I can view to see what the issue might be?

**Comment by drmrbrewer** [comment]
Or maybe I misunderstood which alerts/alarms get notified by email and which don't?  Is only a subset of the alerts you see in the console actually sent as an email notification?

**Comment by titpetric** [comment]
Seems to be an user issue, consult official netdata docs about setting up mail alerts and such.

**Comment by ktsaou** [comment]
In case it helps, netdata runs `sendmail -t` to send the alarms. So, the emails are given to the system MTA, to be dispatched.

@titpetric are these `SSMTP_*` environment variables used by the container?

**Comment by titpetric** [comment]
Yup, SSMTP is installed in the docker image providing mail delivery via an external server (like gmail). Also installed are `sendmail`, `mail` and in fact mail can be sent from a netdata instance (verified by hand).

For example, running netdata like:

```
docker run -it --rm -e SSMTP_TO="black@scene-si.org" -e SSMTP_SERVER=redacted -e SSMTP_PORT=25 -e SSMTP_TLS=NO --entrypoint=/bin/bash titpetric/netdata
root@052ac58d6121:/# perl -pi -e 's/^exec.+/exec bash/g' run.sh && ./run.sh
cp: cannot stat '/etc/netdata/override/*': No such file or directory
root@a2bd5d7a2b81:/# printf "Subject: test sendmail\n\nmail body here" | sendmail black@scene-si.org
```

![image](https://user-images.githubusercontent.com/233360/36105464-f49b0d22-1014-11e8-93d1-3db99dfd8151.png)

mail gets delivered fine, so it's up to the user to follow netdata docs, or verify provided credentials/information. Easiest way to verify is execing into the container after running:

```
docker exec -it netdata bash
# ssmtp mail@to
Subject: test subject
mail body
(empty line - enter)
```

Any errors should be printed at this point, for example:

```
ssmtp: Authorization failed (535 5.7.8  https://support.google.com/mail/?p=BadCredentials b136sm4886338wme.34 - gsmtp)
ssmtp: Server didn't like our AUTH LOGIN (503 5.5.1 Error: authentication not enabled)
...
```

I believe this is purely either a configuration issue of SSMTP credentials, or a configuration issue in setting up netdata alarms themselves (ie, enabling email delivery, etc.).

**Comment by drmrbrewer** [comment]
@titpetric OK thanks.  With some tweaking I have now managed to receive a couple of emails from NetData.  You'll see from my OP that I have an env var `SSMTP_HOSTNAME` set to a human-readable tag for the host.  The intention is that this would appear in the warning email, so that it's easy to determine quickly which server is faulting.  At present, the email subject has the NetData container ID as the identification (which is OK so far as it goes), rather than what I set for `SSMTP_HOSTNAME`... is there an env var I'm missing where I can set a human-readable host name?

**Comment by titpetric** [comment]
![image](https://user-images.githubusercontent.com/233360/36107492-8abf6384-101a-11e8-9907-065f2ea127a3.png)

SSMTP_HOSTNAME is the correct variable.

**Comment by drmrbrewer** [comment]
I can't see that `SSMTP_HOSTNAME` appear anywhere in my notification email.  In the details of the email (gmail) I see:

	from:	root <my-non-gmail-address@mydomain.co.uk>
	to:	root
	bcc:	another-email@gmail.com
	date:	12 February 2018 at 09:20
	subject:	5c9b70023504 recovered - out of disk space time - disk_space._
	mailed-by:	gmail.com

So the email has a blank `to` address (name is `root` but email address is empty.  Instead, the email has been bcc'ed to the email specified in the `SSMTP_TO` variable.  But I can't see `SSMTP_HOSTNAME` anywhere.

**Comment by titpetric** [comment]
So what is `mydomain.co.uk` if not `SSMTP_HOSTNAME`?

**Comment by drmrbrewer** [comment]
I've had `my-non-gmail-address@mydomain.co.uk` set as the `Reply-to address` for a long time now in my gmail account, i.e. the gmail account that I'm using as `SSMTP_USER=my-email@gmail.com` in NetData to send emails.  So `my-non-gmail-address@mydomain.co.uk` must be coming from my gmail settings, not from anything I've given to NetData.  As mentioned, `SSMTP_HOSTNAME` is not surfacing anywhere that I can see.

**Comment by titpetric** [comment]
Seems you have your answer as to why it doesn't work. I'd suggest disabling that setting and testing out netdata alerts with the setting disabled. There are also a number of other services (not-email, possibly *also* email) which you can use for notifications.

**Comment by drmrbrewer** [comment]
OK.  Is there a way to trigger an alert, for testing... other than giving the server a kick to generate a genuine alert condition?

Also, I can't see where to set thresholds for the email notifications.

**Comment by titpetric** [comment]
https://github.com/firehol/netdata/wiki/health-monitoring

**Comment by drmrbrewer** [comment]
So I changed the setting in my gmail account to remove any "reply to" or "send as", and sent a test alert as set out in [the wiki](https://github.com/firehol/netdata/wiki/email-notifications#configuration).

I get:

	from:	netdata <my-email@gmail.com>
	to:	root
	date:	12 February 2018 at 18:07
	subject:	5c9b70023504 is critical - test alarm - test.chart
	mailed-by:	gmail.com
	Signed by:	gmail.com
	security:	 Standard encryption (TLS) Learn more

i.e. 'to' is still 'root' but blank, and I cannot see `SSMTP_HOSTNAME` anywhere.

**Comment by drmrbrewer** [comment]
OK in gmail if I "show original" I get more detailed information:

	Return-Path: <my-email@gmail.com>
	Received: from server-01 (static.redacted. [redacted])
			by smtp.gmail.com with ESMTPSA id redacted
			for <another-email@gmail.com>
			(version=TLS1 cipher=AES128-SHA bits=128/128);
			Mon, 12 Feb 2018 10:07:08 -0800 (PST)
	Message-ID: <redacted@mx.google.com>
	From: netdata <my-email@gmail.com>
	X-Google-Original-From: "netdata" <netdata@server-01>
	Received: by server-01 (sSMTP sendmail emulation); Mon, 12 Feb 2018 18:07:06 +0000
	Date: Mon, 12 Feb 2018 18:07:06 +0000
	To: root
	Subject: 5c9b70023504 is critical - test alarm - test.chart
	MIME-Version: 1.0
	Content-Type: multipart/alternative; boundary="multipart-boundary"

So the `SSMTP_HOSTNAME` (which I set to `server-01`) is present in the above information, but it's clearly not configured in a way that enables the information to be presented to the end user (me) in any obvious way.
