### ISSUE TITLE
Docker hub image updated 21 hours ago. What changed?

### ISSUE THREAD

**Issue by heikkis** [titpetric/netdata#65]
Git repository does not have any updates. Is there way for user to know what is changed?

![image](https://user-images.githubusercontent.com/1392264/36886933-67cb6ef0-1df7-11e8-9ed6-bad7c46eefa5.png)

![image](https://user-images.githubusercontent.com/1392264/36886941-7356b0d6-1df7-11e8-89fa-57a6fe7fbc2e.png)

**Comment by titpetric** [comment]
It's build based on the parent repository, [firehol/netdata](https://github.com/firehol/netdata). There's a full changelog there, albeit there were no changes in the 1.9 branch as it's pinned to an exact commit with a tag.

**Comment by heikkis** [comment]
Thank for info. IMHO I dislike the way docker images are updated on the fly for same version tag.

**Comment by titpetric** [comment]
I did disable the 1.9 build, so it won't rebuild anymore (it's pointless, I agree). It's unfortunately a limitation of docker hub that it rebuilds everything with a push to master, even if the tags didn't change/don't point to a new commit.
