### ISSUE TITLE
SmartHDD monitoring of host inside container [documentation]

### ISSUE THREAD

**Issue by LeeNX** [titpetric/netdata#67]
Hope this helps somebody else and put into language that others can read. Thanks @titpetric for your repo, really helped me get my first netdata docker up and running, though maybe a little more complete example might be more helpful for a beginner, like me ... ;-)  
  
If you wish to monitoring your SMARTHDD attribs for your HOST Hard drives, you can mount (is that the correct term?) the attrib folder inside of the docker container. ie my Debian host saves the attribs in the /var/lib/smartmontools
```
leet@nexus:/opt/netdata$ ll /var/lib/smartmontools/
total 6648
-rw-r--r-- 1 root root   52892 Jun 27  2017 attrlog.ST1000DM003_1CH162-S1D9YTMQ.ata.csv
-rw-r--r-- 1 root root   50377 Jun 27  2017 attrlog.ST31500341AS-9VS226NZ.ata.csv
-rw-r--r-- 1 root root  317439 Jan 18 02:43 attrlog.ST31500341AS-9VS2C0HH.ata.csv
```
by adding ``` -v /var/lib/smartmontools:/var/lib/smartmontools:ro``` to my docker run command, I can just point ```netdata``` at the local folder ... Mmm,  if you name it as netdata expects it, you will not need to do any pointing.  
````
-v /var/lib/smartmontools:/var/log/smartd:ro
````
I also excluded this path from netdata monitoring, so it does not look as messy.

**Comment by titpetric** [comment]
If you would include this as a section in the README.md, it would be great. Can you submit a PR?

**Comment by titpetric** [comment]
Closing because inactive.
