### ISSUE TITLE
Include fping in the docker image, please? [feature request]

### ISSUE THREAD

**Issue by LeeNX** [titpetric/netdata#68]
Please can you include ```fping``` in the docker image.  
  
I understand the need to keep the docker image as lean as possible, but been able to fping from within the ```netdata``` container would be really great ... Else, maybe make a note that fping is not included. I wasted too much time thinking it might have been, but that is because I am a very newbie docker user.  
  
Thanks!

**Comment by titpetric** [comment]
Can you make a case why fping should be included for everyone?

**Comment by titpetric** [comment]
Nvm, it's such a small dependency (<40kb), so that I've added it to the latest & 1.10 tags. Closing the issue.

**Comment by LeeNX** [comment]
@titpetric - Thanks!

**Comment by sazarkin** [comment]
It looks like you got an old version of fping.
You need 4> to support netdata flag.

Can be installed like this:
```/usr/libexec/netdata/plugins.d/fping.plugin install```
From https://github.com/firehol/netdata/wiki/fping-Plugin

**Comment by ShagoY** [comment]
Hi titpetric :)

The latest docker image netdata (version: 1.10.1_rolling / commit: 2087ce0) seems don't have exec /usr/local/bin/fping, it's  expected ?

Regards.
