### ISSUE TITLE
Missing JS as of latest update

### ISSUE THREAD

**Issue by nexusmaniac** [titpetric/netdata#69]
Errors:
`Cannot load required JS library: http://192.168.86.253:19999/dashboard_info.js?v20180510-2`
`Cannot load required JS library: http://192.168.86.253:19999/lib/perfect-scrollbar-0.6.15.min.js`

Version: `v1.10.0-129-g36bedc0_rolling`

Just update a few minutes ago and now I'm seeing this error message in Chrome and Edge.

I've tried restarting the container with no success :)

Anything I can provide to help diagnose the issue? :)

**Comment by ktsaou** [comment]
not missing. was faulty.
fixed it upstream. I am not sure how you should update...

**Comment by titpetric** [comment]
@ktsaou since you're following semver, tag a new release with a patch version, v1.10.1.

**Comment by titpetric** [comment]
~~Also, I think it was my problem. I was building against the master branch instead of v1.10.0 (which i suspect doesn't have this problem). I'm gonna rebuild that one, no need to tag v1.10.1.~~ Edit: nope, building against the correct tag/branch.

**Comment by ktsaou** [comment]
yes, the problem was not included in a release. Just a problematic PR that managed to get through all our checks....

**Comment by titpetric** [comment]
@nexusmaniac are you running netdata:latest? if yes, then a `docker pull` will pull a new version (it was built about half an hour ago). If you want some stability, you might want to switch to netdata:1.10 until the next version is released. Or just wait a bit and pull a new version when it's built. I just manually triggered both the 1.10 build and the latest one, which should bring them up to date;

**Comment by nexusmaniac** [comment]
Yep, I'm on `titpetric/netdata:latest` :)

It's not massively unstable for me usually, I'll probably stick with the latest for now, cheers for letting me know though! 👍 
I think I can hold off moving to `:1.10` for now but I'll keep it in mind :) Thanks for being super responsive!

**Comment by nexusmaniac** [comment]
Just spotted that `latest` rolled back :)

`v1.10.0-131-g95e50ae_rolling` Guessing it matches the last `1.10` build? JS issue has vanished 😄

**Comment by bv-ritesh** [comment]
Getting following error with Netdata version: **v1.19.0-214-nightly** while accessing the dashboard

Cannot load required JS library: http://abc.bdc.com/host/501/lib/perfect-scrollbar-0.6.15.min.js

Any help would be appreciated. 

Regards,
Ritesh
