### ISSUE TITLE
Alpine based base image

### ISSUE THREAD

**Issue by MaicoTimmerman** [titpetric/netdata#70]
The debian:jessie base image is over 100MB's. Could you perhaps also support a alpine based image?

**Comment by titpetric** [comment]
If you're willing to produce some dockerfiles for it along the same lines as the docker one, I am open to fielding a PR. All you'd need to do is provide a Dockerfile.alpine under `releases/dev` and I can take it from there. It's also possible to use a multi-stage build file now, to build netdata from source without having to resort to some of the tricks I used here to keep the size down.

**Comment by nexusmaniac** [comment]
I was just heading here to ask for the same!! Perfect timing @MaicoTimmerman 😉 

@titpetric https://github.com/firehol/netdata/blob/master/Dockerfile.alpine

The reason I stick with your Netdata Docker Container vs Firehol's is because you parse the other container names perfectly from `docker.sock` on my unRAID host - so having Alpine in addition to your excellent Netdata checkout would be perfect 👌 

Hope that the linked dockerfile helps 😁

**Comment by ktsaou** [comment]
> you parse the other container names perfectly from docker.sock

Both dockerfiles have been created by @titpetric (which of course rocks!)

@titpetric could you please make a PR to fix it at the official repo too?

**Comment by titpetric** [comment]
@nexusmaniac what do you mean by "parse the other container names"? ;).

The alpine image wasn't created by me, and it also seems that it's a bit un-optimal in the sense of how it's built, as it doesn't seem to do any cleanup of build resources which I see at first glance. When I get the time to stab around it and produce my own alpine fork, I'll make sure to PR the changes to the official repo as well. Alas, I don't know when that might be, so any help is appreciated, I'm more than happy to field some PRs.

**Comment by nexusmaniac** [comment]
@titpetric 

Right hand side, the metrics from other Docker Containers 👍 

```
Container resource utilization metrics. Netdata reads this information from cgroups (abbreviated from control groups), a Linux kernel feature that limits and accounts resource usage (CPU, memory, disk I/O, network, etc.) of a collection of processes. cgroups together with namespaces (that offer isolation between processes) provide what we usually call: containers.
```

I passthrough the `docker.sock` file to Netdata, `/titpetric/netdata/` parses the container names correctly, `/firehol/netdata/` gets the raw container name (i.e. `f6453277aaed` instead of `duckdns` 😄)

![image](https://user-images.githubusercontent.com/4521949/40886339-cd8a16b8-672d-11e8-8343-2045d9a89977.png)

**Comment by titpetric** [comment]
Can you exec into the running container and issue a `ps aux` or similar which will print the user under which netdata is running. Also please issue `ls -la /var/run/docker.sock` (or whereever it is, I don't remember the location by heart).

Likely: netdata is running as non-root. You'd have to add the ID of the netdata user into the docker group. Usually docker.sock is chmod 660, chown root.docker, meaning the only access is possible as the root user, or as an user who is a member of the docker group. No global access is permitted by default.

Second option, you can expose a more permissive docker.sock using [docker-proxy-acl](https://github.com/titpetric/docker-proxy-acl). It's a bit of a pain, but better wide open access.

**Comment by nexusmaniac** [comment]
From host:
```
root@Raptor:~# ls -lah /var/run/docker.sock
srw-rw---- 1 root docker 0 May 19 09:32 /var/run/docker.sock=
```
Inside container:
```
# ls -lah var/run/docker.sock
srw-rw---- 1 root 281 0 May 19 09:32 var/run/docker.sock
```
```
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.8  0.2  98548 37860 ?        Ssl  04:05   4:55 /usr/sbin/netdata -D -u root -s /host -p 19999
root        35  1.3  0.1 414556 23940 ?        Sl   04:05   7:49 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugiroot      9545  0.1  0.0  20252  3104 ?        S    13:06   0:03 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
root     10425  0.0  0.0   4340   768 pts/0    Ss   13:59   0:00 sh
root     10496  0.0  0.0  17504  2080 pts/0    R+   14:02   0:00 ps aux
```

The Netdata container runs as non-root, for some reason the Firehol Netdata container doesn't read the container names from `docker.sock` without me chmod'ing it to something like 660, as you suggested.

Should I get both the Titpetric & Firehol containers up and running in order to figure out what's up here? 😄 

I don't believe I can alter groups on unRAID (and have them persist) I'll have to look into that for the long run.

**Comment by titpetric** [comment]
The ps auxw was from titpetric/netdata or firehol? Seems like mine, you should perform the commands on firehol/netdata ;) seems like the `-u root` switch will be missing, so at least you know what you need to figure out, if that's the case.

**Comment by nexusmaniac** [comment]
That was `titpetric/netdata` 😄 

------

Here's `firehol/netdata`

```
/ # ls -lah /var/run/docker.sock
srw-rw----    1 root     281            0 May 19 08:32 /var/run/docker.sock
```

```
/ # ps aux
PID   USER     TIME   COMMAND
    1 netdata    0:01 /usr/sbin/netdata -D -s /host -p 19999
   32 netdata    0:01 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
  493 root       0:00 sh
  500 root       0:00 ps aux
```

Looks like `-u root` is missing!

And on Firehol it looks like this 😛 

![image](https://user-images.githubusercontent.com/4521949/40919985-2223926e-6803-11e8-8b24-26a744de0c5c.png)

**Comment by titpetric** [comment]
It's the issue of the upstream CMD:

> The main purpose of a CMD is to provide defaults for an executing container. These defaults can include an executable, or they can omit the executable, in which case you must specify an ENTRYPOINT instruction as well.

The upstream provides both the executable and arguments in CMD, unlike this image which takes a number of custom parameters in addition to the default ones. The good news is, that you can get around it for your case quite easy, something like this:

```
docker run -it -d [... usual args ...] firehol/netdata /usr/sbin/netdata -D -u root -s /host -p 19999
```

So, you at least have a work around.

**Comment by nexusmaniac** [comment]
I've tried to figure out what you're suggesting... Turns out I'm unable to do this on my Docker host (unRAID)

If I could use the dockerfile to create a container on unRAID, this would be possible.

But `CMD /usr/sbin/netdata -D -s /host -p ${NETDATA_PORT}` that's the line I'd need to change in the Firehol dockerfile (https://hub.docker.com/r/firehol/netdata/~/dockerfile/)

unRAID is very GUI heavy and doesn't allow for a massive amount of tinkering, unfortunately.

For others this may be a workaround but I'll have to live without 😛 Unless I post an 'issue' on the Firehol git repo and request that `-u root` is added to the alpine dockerfile? 😄

**Comment by titpetric** [comment]
Why are you unable to do it? Can you not pass custom arguments to the docker image you're trying to run?

**Comment by nexusmaniac** [comment]
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='netdata_firehol' --net='host' -e TZ="Europe/London" -e HOST_OS="unRAID" -v '/mnt/user/appdata/netdata_f/':'/etc/netdata':'rw' -v '/proc':'/host/proc':'ro' -v '/sys':'/host/sys':'ro' -v '/var/run/docker.sock':'/var/run/docker.sock':'ro' --cap-add SYS_PTRACE --log-opt max-size=50m --log-opt max-file=1 'firehol/netdata:alpine' /usr/sbin/netdata -D -u root -s /host -p 19999
a376c7ece072ee00b8dbb95a4fbea45220cea8e6109d4c62a44d26eaa87800a3

The command finished successfully!
```

But upon adding that to the `Post Arguments:` in unRAID I get this:
`Access to file is not permitted: /usr/share/netdata/web//index.html`
When I go to the Netdata 'site' 😢 

----

But if I take a look inside the container again...

```
/ # ls -lah /var/run/docker.sock
srw-rw----    1 root     281            0 Jun 13 07:33 /var/run/docker.sock
/ # ps aux
PID   USER     TIME   COMMAND
    1 root       0:01 /usr/sbin/netdata -D -u root -s /host -p 19999
   31 root       0:01 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
  465 root       0:00 sh
  472 root       0:00 ps aux
/ #
```

It's definitely worked 😛 (I just can't access the webUI side of things 🤔

**Comment by nexusmaniac** [comment]
@titpetric Any logs I can obtain to help us diagnose this weird lack of WebUI access once running the 'custom' args at the end? (`docker run -it -d [... usual args ...] firehol/netdata /usr/sbin/netdata -D -u root -s /host -p 19999`)

Give us a shout and I'll help out 😄

**Comment by titpetric** [comment]
I believe it's a security consideration from @ktsaou, that the files under /usr/share/netdata/web must match the owner that netdata is running as. The restriction is a bit silly, given that it should validate against user *OR* group, or even neither and just honor what is most likely a global readable file (a+r).

I understand that it's somewhat of a hack just to keep things more secure. Would it be possible not to match the running user, but a set of ["root", "netdata"], which are the two common users (I asume also the files are owned by either root.netdata or netdata.netdata, so they are both readable).

**Comment by nexusmaniac** [comment]
@titpetric 

I've just gone inside the container again:
`chown -R root:root /usr/share/netdata/web/` ! It works 👍 😄 The WebUI is reachable again and the Docker Container (Cnames) are all properly decoded 😉 

Just need to work out a way to make that `chown` command run automatically 😛 In its current form, I'll need to run it manually every time there's an update to this Netdata container 🤔

**Comment by titpetric** [comment]
try with `bash -c`:

~~~
docker run -it -d [... usual args ...] firehol/netdata bash -c 'chown -R root:root /usr/share/netdata/web/ ;  /usr/sbin/netdata -D -u root -s /host -p 19999'
~~~

Ugly as *heck*, bit it should work.

**Comment by nexusmaniac** [comment]
Perfect 👌 Thanks @titpetric 

I had to alter it slightly (`bash -c 'chown -R root:root /usr/share/netdata/web/ &&  /usr/sbin/netdata -D -u root -s /host -p 19999'`) for `&&` instead of `;` but other than that it's perfect! 👍 

Cheers 😄 I'm up and running with Firehol's Alpine Docker Container!

**Comment by titpetric** [comment]
one more thing, try adding `exec` before `/usr/sbin/netdata` (ie, `&& exec /usr/sbin/netdata...`). You want netdata running as PID 1 in the container, so it will shutdown / receive signals gracefully. Give another `ps` check when you do, to verify.

**Comment by nexusmaniac** [comment]
```
bash-4.4# ps aux
PID   USER     TIME   COMMAND
    1 root       0:00 /usr/sbin/netdata -D -u root -s /host -p 19999
   35 root       0:01 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
  477 root       0:00 bash
  483 root       0:00 ps aux
bash-4.4#
```

Seems it was already running as PID 1 - but I've added exec now and it's all still working 😁

**Comment by pgassmann** [comment]
The actual issue is that in the alpine image, the `netdata` user is not in the `docker` group.

image: titpetric/netdata:latest
or 
image: firehol/netdata
=> container names OK

```
# ps aufx
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       607  0.0  0.1  18188  2928 pts/0    Ss   18:59   0:00 /bin/bash
root      1814  0.0  0.1  36640  2828 pts/0    R+   19:01   0:00  \_ ps aufx
netdata      1  1.2  2.0 185452 41676 ?        Ssl  18:58   0:02 /usr/sbin/netdata -D -s /host -p 19999
netdata     18  0.3  0.1  18164  2244 ?        S    18:58   0:00 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
root        29  1.7  0.1  19540  2636 ?        S    18:58   0:02 /usr/libexec/netdata/plugins.d/apps.plugin 1


# ls -lha /var/run/docker.sock 
srw-rw---- 1 root netdata 0 Jun 17 14:45 /var/run/docker.sock

# id netdata
uid=999(netdata) gid=999(netdata) groups=999(netdata),4(adm),13(proxy)
```

image: firehol/netdata:alpine
-> container names MISSING

```
# ps aufx
PID   USER     TIME  COMMAND
    1 netdata   0:01 /usr/sbin/netdata -D -s /host -p 19999
   26 root      0:01 /usr/libexec/netdata/plugins.d/apps.plugin 1
  534 root      0:00 /bin/bash
  540 root      0:00 ps aufx
# ls -lha /var/run/docker.sock
srw-rw----    1 root     ping           0 Jun 17 14:45 /var/run/docker.sock

# id netdata
uid=101(netdata) gid=101(netdata) groups=101(netdata),101(netdata)

# tail /etc/group
ntp:x:123:
nofiles:x:200:
smmsp:x:209:smmsp
locate:x:245:
abuild:x:300:
utmp:x:406:
ping:x:999:
nogroup:x:65533:
nobody:x:65534:
netdata:x:101:netdata
```

In alpine the group `ping` has gid 999 (docker)

**Comment by pgassmann** [comment]
the correct fix is to add netdata to the ping group which has gid 999 in alpine:

`addgroup netdata ping`

should be added to https://github.com/firehol/netdata/blob/master/Dockerfile.alpine#L44

or workaround: 
command: `bash -c 'addgroup netdata ping && exec /usr/sbin/netdata -D -s /host -p 19999`

**Comment by pgassmann** [comment]
I use the following docker-compose.yml file to run netdata without `fakenet.sh`
for use with letsencrypt-nginx-proxy-companion by Evert Ramos
https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

## docker-compose.yml
```
# docker-compose.yml
# netdata in docker container with access to host network (for network metrics).
# for use with letsencrypt-nginx-proxy-companion by Evert Ramos
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
# uses socat to proxy netdata to reverse proxy
# a separate network is defined to bind netdata to a fix ip address
# this ip address is used for the socat target
#
version: '3'
services:
  netdata:
    image: firehol/netdata:alpine
    hostname: example.com # set to fqdn of host
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./netdata.conf:/etc/netdata.conf:ro
    network_mode: host
    # add netdata to ping group (gid 999) for access to docker.sock
    command:  bash -c 'addgroup netdata ping && exec /usr/sbin/netdata -D -s /host -p 19999 -i 192.168.88.1'

  socat:
    image: alpine/socat:latest
    environment:
      - VIRTUAL_HOST=netdata.example.com
      - LETSENCRYPT_HOST=netdata.example.com
      - LETSENCRYPT_EMAIL=your_email@domain.com
      - VIRTUAL_PORT=19999
    entrypoint: socat TCP-LISTEN:19999,nodelay,fork,reuseaddr TCP:192.168.88.1:19999
    expose:
      - 19999
    networks:
      - webproxy
      - netdata

networks:
  webproxy:
    external:
      name: webproxy
  netdata:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24
```

## Security
The [letsencrypt-nginx-proxy-companion](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) comes with **automatic basic auth support.**
just add a htpasswd file at `./data/htpasswd/netdata.example.com` in the _webproxy_ project!
https://github.com/jwilder/nginx-proxy#basic-authentication-support

**Comment by titpetric** [comment]
This issue went offtopic fast, but just to clarify, titpetric/netdata won't support an alpine base image any time soon. Check the `netdata/netdata` image if they suit your cases better.
