### ISSUE TITLE
Clarify licensing for Dockerfiles.

### ISSUE THREAD

**Issue by Ferroin** [titpetric/netdata#71]
I'm currently in the process of putting together a PR for Netdata that properly tags as many of the files it includes as possible with licensing information.

The Dockerfiles that are included there based on this project (from almost two years ago) are on the short list of files I've not found any licensing information for at all.

It would be appreciated if you could clarify what license these are under, or if not whether it's OK to mark them as GPL-3.0 or newer.

**Comment by titpetric** [comment]
If anything the license might be inherited from firehol/netdata, or it's going to be WTFPL unless there's some PG-rating opinion against the WT(F)PL :). Opinion @ktsaou?

**Comment by titpetric** [comment]
netdata is GPL-3.0, if you're tagging together a PR, it's fine to submit a GPL3 version - generally I'm not a big fan of GPL, but apparently putting something into public domain has it's own separate set of issues. Who knew?

**Comment by Ferroin** [comment]
If you really want it to be public domain, [CC0](https://creativecommons.org/publicdomain/zero/1.0/) would probably be the best option.  It's not perfect, but it covers things as far as possible in an international manner.

Netdata actually already has some things it's redistributing that are CC0 (the icons), so If you wanted to go that way it shouldn't be an issue to just tag the files as such.

**Comment by titpetric** [comment]
Yeah, sure, CC0 sounds good. I'll wait a bit for @ktsaou to pitch in, but generally I'm fine with that. I'll throw the LICENSE file in there within a couple of days :)

**Comment by titpetric** [comment]
@Ferroin if you're stil up to adding the license file info as a PR, feel free to add it as a CC0. It's going to be faster than waiting for me. TY
