### ISSUE TITLE
msmtp not setting FROM header

### ISSUE THREAD

**Issue by kmlucy** [titpetric/netdata#72]
With the switch to msmtp, my emails have broken. There are two main problems that I have found. The first is easily corrected. ``auth on`` needs to be set in the configuration file if there is a username provided. This can be put after this line: https://github.com/titpetric/netdata/blob/d193efd858165266a77f087882e52838bb0c91e1/releases/latest/scripts/run.sh#L28

The second issue is that msmtp isn't setting the 'from' header. Because of this, emails sent to gmail addresses get blocked:
```
 Our system has detected that this message is 5.7.1 not RFC 5322 compliant: 5.7.1 'From' header is missing. 5.7.1 To reduce the amount of spam sent to Gmail, this message has been 5.7.1 blocked. Please visit 5.7.1 https://support.google.com/mail/?p=RfcMessageNonCompliant 5.7.1 and review RFC 5322 specifications for more information. 13-v6si660070qtt.40 - gsmtp
```
There appears to be an option in the version of msmtp included with Debian Stretch, but not included in Jessie, that would fix this: 
```
‘add_missing_from_header [(on|off)]’
This command controls whether to add a From header if the mail does not have one. The default is to add it. See Header handling.
```
Therefore, I would recommend either moving to Stretch as the base image, or moving back to sSMTP.

**Comment by titpetric** [comment]
Thanks for your PR, it's much appreciated. Moving to stretch was also on the list, because of an outdated `fping` (hopefully stretch provides a 4.x, I'm not tempted to move further towards the unstable branches).
