### ISSUE TITLE
Automatic Build on hub.docker.com spams autoupdated installs

### ISSUE THREAD

**Issue by wofnull** [titpetric/netdata#77]
Hello, 

i do use your docker image over on https://hub.docker.com/r/titpetric/netdata/

However, I use aswell an automated script , which pulls every 10 minutes ( if there is a newer version ) a fresh copy from your docker container.

as it looks, for a while now, your container over on the docker hub does compile a "latest" image and then an 1.11 image, which does currently not exists and then fails to build, leading to rebuild the latest image again, which leads the system to pull again a fresh copy from the docker container over and over again.

Could you please take a look into this, since this particular image is very usefull for me and on the other hand it now does need a fairly large amount of space on my server.

![netdata](https://user-images.githubusercontent.com/449003/46068456-7bfa3980-c179-11e8-8725-e61fbb9528f0.PNG)
![netdata2](https://user-images.githubusercontent.com/449003/46068457-7bfa3980-c179-11e8-85b9-564b784016e5.PNG)

**Comment by andrebnc** [comment]
Same problem here. :(

**Comment by titpetric** [comment]
Going to check it out during next days. Thanks for your patience.

Best,
Tit

**Comment by andrebnc** [comment]
Problem still exists.

**Comment by titpetric** [comment]
I removed the 1.11 tag after building it. Don't use `:latest` unless you want cutting edge images. I'm considering this as resolved. OP uses `netdata:latest` which means you get a new version on pretty much any changes in the upstream source code. Use `netdata:1.11` or `netdata:1.10` (there's some reported alarms issue in netdata 1.11).

**Comment by smcpeck** [comment]
This still happens.  It seems that the automated build is on a timer maybe and doesn't care if there is already a build out there for the most recent commit hash.

Why all the builds from the exact same commit?

![image](https://user-images.githubusercontent.com/8724583/54381961-00277700-465d-11e9-8ebc-55efaee71d30.png)
