### ISSUE TITLE
What is the advantage of using this image over the official one?

### ISSUE THREAD

**Issue by githubsaturn** [titpetric/netdata#79]
Now that netdata has their own image on DockerHub, is there still any benefit for using this image?

Official netdata docker image:
https://hub.docker.com/r/netdata/netdata/

Announcement was part of 1.11.0, under packaging:
https://github.com/netdata/netdata/releases/tag/v1.11.0

**Comment by titpetric** [comment]
If you don't know which to use, you're going to get support on the upstream faster today than on this one.
