### ISSUE TITLE
Out of sync with the official netdata releases

### ISSUE THREAD

**Issue by cakrit** [titpetric/netdata#83]
Hi @titpetric, 

A lot has changed in the netdata release process in the last 3 months, so I see a "release" 1.12.0-rc0 that wasn't really an official release. I'd love to have a chat on how we use the various tags and what is considered an official release, so you can have the officially supported versions here as well. Please contact me directly at chris@netdata.cloud and we will arrange a quick call whenever is good for you.

Regards,
Chris

**Comment by noplanman** [comment]
Adding to this, it would be great if there was a docker tag for each release, not just "latest".

**Comment by titpetric** [comment]
@noplanman there are tags for each release https://hub.docker.com/r/titpetric/netdata/tags  - but as the issue mentions, this repo is behind the times a bit. I'll check out if I can automate adding new versions, but generally it takes some manual work to set up automated builds on docker hub for each version. TBD

**Comment by cakrit** [comment]
Just note that we'll never have an official release tagged with "-rcX". These are release candidates that are just aligned to our sprints, so we can have some clear milestones. The official releases will always be tagged with vX.Y.Z, so the last one is v1.12.2, the one before it v1.12.1 etc. and can always be seen under https://github.com/netdata/netdata/releases

**Comment by noplanman** [comment]
@titpetric Right, so "latest" is just more recently built on docker hub but is actually just 1.11 still, yes?

I noticed you have that pretty `update-releases.sh` script :innocent:

**Comment by titpetric** [comment]
@cakrit - sure, agreed. I'll filter out `-rc` from the automated releases.

**Comment by titpetric** [comment]
- moved to use git tags in this repo as well to cut down on manual interaction on docker hub
- waiting to see if docker hub actually builds the tags now
- docker hub is sloooooowwwwww (but free, eh)

**Comment by titpetric** [comment]
Docker does pick up tags, but I still do have to update them manually. With some recent development, that's bound to happen more often now :)

**Comment by SuperSandro2000** [comment]
I suggest using travis if the build time is under 50 minutes. I replaced Docker Hub fully with travis and some scripts cause it sometimes takes an hour to even start the build process.
