### ISSUE TITLE
Redundant Automatic Builds

### ISSUE THREAD

**Issue by smcpeck** [titpetric/netdata#84]
I mentioned this in #77 as it seems to be a similar issue, but figured I'd open something brand new for tracking and hopefully so it gets some eyes.
________________________________________________
It seems that the automated build is on a timer maybe and doesn't care if there is already a build out there for the most recent commit hash.

Why all the builds from the exact same commit?  This causes my environment to update netdata many times a day and I end up with tons of images just littering my system and taking up space.

![image](https://user-images.githubusercontent.com/8724583/54383122-5bf2ff80-465f-11e9-898c-4ac8dee9495a.png)

**Comment by SuperSandro2000** [comment]
This happens with my personal images, too.
If any of the layers updates then the image gets updated. Netdata sources get changes almost every day so the image gets rebuild a lot.

**Comment by titpetric** [comment]
Commit source points to titpetric/netdata and not netdata/netdata, so this is expected behaviour. The upstream change doesn't trigger a commit source change in titpetric/netdata.

If you want a stable version, use a tagged release, like `titpetric/netdata:1.11`.
