### ISSUE TITLE
Support for dbengine

### ISSUE THREAD

**Issue by dcflachs** [titpetric/netdata#88]
Attempting to enable Netdata's new dbengine memory mode fails with the following error RRD_MEMORY_MODE_DBENGINE is not supported in this platform. Based on a little digging here [https://github.com/netdata/netdata/](https://github.com/netdata/netdata/) and here [https://docs.netdata.cloud/packaging/installer/#one-line-installation](https://docs.netdata.cloud/packaging/installer/#one-line-installation) i think your image may be missing a few new netdata dependencies. Possibly libuv, liblz4, Judy, and openssl

**Comment by dcflachs** [comment]
@titpetric

**Comment by titpetric** [comment]
Hello! The best way to get this in would be to submit a PR adding the dependencies, or to explain better how you're encountering the failure (ie, a way to replicate). I am using netdata in production currently, but configured differently, so I'm not hitting your limitation.

Extending the issue with more information / way to reproduce would be appreciated.

**Comment by dcflachs** [comment]
Yes sorry for being light on the information. I believe this issue can be reproduced by adding 
`memory mode = dbengine`
to the `[global]` section of 

> netdata.conf

. 
If things were working correctly this would enable the new database engine memory mode for netdata. Instead netdata will refuse to start. I can provide the whole docker log is neccissary but i believe that relevant line is 
`2019-08-20 20:57:39: netdata FATAL : MAIN :RRD_MEMORY_MODE_DBENGINE is not supported in this platform. # : No such file or directory`
According to the links i posted in my first comment this seems to be indicative of missing dependencies.

**Comment by titpetric** [comment]
PR merged, need to verify the build(s) sometime and will close this issue when done. Might take a while before I get to that tho. If it works for you, just close it :) Thanks.

**Comment by dcflachs** [comment]
Thanks for getting this merged. Everything appears to be working fine in with the DBEngine memory mode.
