### ISSUE TITLE
Update to 1.20?

### ISSUE THREAD

**Issue by lordraiden** [titpetric/netdata#92]
The docker hasnt been updates in 3 months while the official dockers got new updates a week ago
https://hub.docker.com/r/netdata/netdata/tags

**Comment by SuperSandro2000** [comment]
1.20 is out since 9 days. I know that sometimes the sorting on Docker HUB is weird. You probably just missed it.

**Comment by titpetric** [comment]
Correct. If you want newer versions, just migrate to the official images. I'm archiving this repository.
